name: Testing
on: 
  push:
    branches: [main]

env:
  MOZ_HEADLESS: true
  GECKODRIVER_VERSION: v0.36.0

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/${{ env.GECKODRIVER_VERSION }}/geckodriver-${{ env.GECKODRIVER_VERSION }}-linux64.tar.gz
          tar -xvzf geckodriver-${{ env.GECKODRIVER_VERSION }}-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
    
      - name: Check Firefox
        run: |
          firefox --version

      - name: Check Geckodriver
        run: |
          geckodriver --version
