name: Testing
on: 
  push:
    branches: [main]

env:
  MOZ_HEADLESS: true

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Firefox
        run: |
          sudo apt update
          sudo apt install -y firefox
