name: Testing
on: 
  push:
    branches: [main]

env:
  MOZ_HEADLESS: true

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Firefox
        run: |
          firefox --version

      - name: Setup Geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.30.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
    
      - name: Check Firefox and Geckodriver
        run: |
          firefox --version
          geckodriver --version